### ISSUE TITLE
there's a problem in batoto

### ISSUE THREAD

**Issue by JiJis18** [fmd-project-team/FMD#1006]
i seem to can't download the manga and i seem to can't update the mangalist from batoto. It's been a month, sorry to report it just now. Thank you for your hardwork.

**Comment by spamtaztik** [comment]
Just now for some weird reason I can check all my favs from batoto, and can add the new chapters to download list. Problem is, most of them are errors. Out of the 10 titles that have new chapters, only 2 can be downloaded. The rest failed. Is there no solution/workaround to this? I tried the cookies/useragent workaround but the problem is still there.

**Comment by Tmp341** [comment]
I think something changed in the code, but there is nobody here to fix that.

**Comment by JiJis18** [comment]
> I think something changed in the code, but there is nobody here to fix that.

OMG !! Thank you so much for the problem fixer. I can update the library again, thank you for you guys hardwork and i hope you guys always healthy :)

**Comment by JiJis18** [comment]
um, i think mine has a problem again ini batoto. Or maybe i should wait a little bit to get to normal again right ?

**Comment by Tmp341** [comment]
Since it worked before, that means batoto has internal problems, or you. Wait a little.
