### ISSUE TITLE
What improvements does fmd2 have compared to fmd1?

### ISSUE THREAD

**Issue by djgerman10** [fmd-project-team/FMD#1037]
[https://github.com/dazedcat19/FMD2](https://github.com/dazedcat19/FMD2)

**Comment by Tmp341** [comment]
Why don't you ask that to him? He is coder, and added a lot of commits in his fork. I don't know anything about coding. 🤷‍♂️

**Comment by mooglestiltzkin** [comment]
if you go here you can compare his fmd2 vs fmd1
https://github.com/fmd-project-team/FMD/compare/master...dazedcat19:master

**Comment by mooglestiltzkin** [comment]
I was looking at fmd project team discord channel and saw someone say this about the fmd2 dev

"Sasuke_UchihaYesterday at 7:11 PM
Any idea how long FMD2 is going to be supported?
If i remember correctly the developer has a reputation for disappearing out of nowhere for years.
I'm a little afraid of migrating since it won't be possible to going back when the project is dropped again"

And this was what another user suggested

"Tmp341Today at 3:37 AM
@Sasuke_Uchiha Maybe 1 day, maybe 3 months, who knows. I don't understand that developer's mindset. Don't delete one for other. Use both. "

**Comment by mooglestiltzkin** [comment]
And here is another difference between the 2 someone noted

"DgraidToday at 3:43 AM
@Slasar41⚓ good, I have a question .. it seems that the site "LHScans" stopped using cloudflare and it already works in "FMD2" but in "FMD" it still doesn't work and they haven't added the fix .. my question is .. it doesn't anymore Will more support be given to "FMD"?"

**Comment by mooglestiltzkin** [comment]
You can also compare how many contributors and their activity here

https://github.com/dazedcat19/FMD2/graphs/contributors

https://github.com/fmd-project-team/FMD/graphs/contributors

**Comment by mooglestiltzkin** [comment]
one difference i noticed. fmd2 does not have madokami support, but fmd1 does o-O:

**Comment by Tmp341** [comment]
> 
> 
> I was looking at fmd project team discord channel and saw someone say this about the fmd2 dev
> And this was what another user suggested
> 
> "Tmp341Today at 3:37 AM
> @Sasuke_Uchiha Maybe 1 day, maybe 3 months, who knows. I don't understand that developer's mindset. Don't delete one for other. Use both. "

I suggested that. :)

**Comment by azraei97** [comment]
What I see is FMD 2 using much updated version of Lazarus and tools Lua
Not sure what else

**Comment by Tmp341** [comment]
Closing this for now.
