### ISSUE TITLE
Mangasee new site

### ISSUE THREAD

**Issue by traitorAIZEN** [fmd-project-team/FMD#1056]
It changed from https://mangaseeonline.us to https://mangasee123.com/
Please fix

**Comment by azraei97** [comment]
Yes Mangasee change site. Can read the info here https://mangasee123.com/discussion/post.php?id=69392

Currently FMD and Tachiyomi not support new Mangasee yet.

**Comment by traitorAIZEN** [comment]
I hope it gets fixed soon because i think it's the only site that uploads the official volumes.

**Comment by azraei97** [comment]
I have good news for you. I able to make new MangaSee works in FMD. The bad news is not all chapter can be download. 

Example:
https://mangasee123.com/manga/The-Magic-Chef-Of-Ice-And-Fire
Ch1~24 can download just fine but other chapter (ch25+) simply FAIL. Open manually in the website was works fine.

Download this file, Copy and PASTE it on FMD Folder > lua > modules
When it say need to replace file because already have file with same name, click overwrite/replace current file.
 
![Untitled](https://user-images.githubusercontent.com/40983245/86230162-4d698800-bbc3-11ea-9e46-5e9f49fbf529.png)

Need someone to make change in the LUA so it can works perfectly all chapter
https://drive.google.com/file/d/1cdFgxbB2EbWqsC8k-IORUWUkZdHiQbHU/view?usp=sharing

**Comment by azraei97** [comment]
I notice the reason why not all chapter in certain manga can be download because FMD not reading "chapter name" correctly.

Example: https://mangasee123.com/manga/The-Magic-Chef-Of-Ice-And-Fire
Ch 1~24 is Label S1 but Ch25 actually LABEL Ch 1 again but additional S2

Example 2: https://mangasee123.com/manga/Real-Account
Ch 1~10 can download FINE but Ch11 actually LABEL Ch 1 again due to publisher decided to reuse / repeat chapter numbering again

**Comment by traitorAIZEN** [comment]
Thanks azraei97. Works perfectly fine for me. I also didn't ecounter the problems you pointed at.

But why did SDXC delete the mangasee.lua and not replace it in the latest module update? It stopped working. Good thing it worked again after re-adding azraei97's mangasee.lua
