### ISSUE TITLE
Can't update kissmanga

### ISSUE THREAD

**Issue by Souravi785** [fmd-project-team/FMD#1061]
There are some new mangas I want to download from kissmanga but I can't update them.

![sample fmd 6](https://user-images.githubusercontent.com/24958560/86527097-57d69b00-bebd-11ea-9dec-d9b9b245ddc3.PNG)

After updating

![image](https://user-images.githubusercontent.com/24958560/86527252-016a5c00-bebf-11ea-9128-74e1ed00f4d7.png)

Manga list is same as before.

**Comment by garybempo** [comment]
in order to download kissmanga with fmd, so far there only manual workarounds
Steps:
1. first open the "Inspect Element" or "Inspect" and open "Network" tab on browser.(so that can easily capture the cookie for step 5 and use browser console in step 4)
2. visit the kissmanga site and view a chapter of manga
3. solve the verification (select 2 pictures)
4. enter "Key"(chko)& "Initialization Vector" on "Option">"Websites">"Option" [ref guide](https://github.com/fmd-project-team/FMD/wiki)
5. go "Option">"Websites">"Advanced">find "kissmanga">tick "Enabled" and get whole cookies list(__cfduid,cf_clearance etc) & user agent [ref guide](https://github.com/riderkick/FMD/wiki/FAQ)
ps: now u need add extra code:"vns_readType1=0" within the cookie list [#issue 934](https://github.com/fmd-project-team/FMD/issues/934)
ps2: no need login to kissmanga

kissmanga is getting annoying so it is better change manga site to download manga.

**Comment by garybempo** [comment]
delete the "KissManga.db" inside the data folder which within fmd installed folder then "update manga list" which will create a new KissManga.db from zero.
ps: this process take a long time (few hours)
ps2: if u kind enough later u can upload to the [FMD-WebsiteDatabases](https://github.com/fmd-project-team/FMD-WebsiteDatabases)

**Comment by Tmp341** [comment]
I think kissmanga changed url structure, so previous databases don't work.

**Comment by Inareous** [comment]
I've made a pull request on [FMD-WebsiteDatabases](https://github.com/fmd-project-team/FMD-WebsiteDatabases/pulls/17), wait until it get approved and then from your fmd use "update from server".

As a side note, current FMD implementation doesn't retry failed links on update, thats why u should use only 1 thread to avoid it. If this happens you end up with incomplete db (maybe add this as another issue).

**Comment by Tmp341** [comment]
Check #1109.
