### ISSUE TITLE
Favorites taking ages to update or don't update at all

### ISSUE THREAD

**Issue by leoteesh** [fmd-project-team/FMD#109]
Hi 
the manga updates is taking a long time to update. nearly a day,
this could be because most of my favorites are from mangago. is there anyway i can make it go quicker?

![image](https://user-images.githubusercontent.com/21075197/56150318-8b6e9200-5fa6-11e9-9e0d-fb4d990a4be1.png)

Many thanks

**Comment by SDXC** [comment]
All your red entries had a timeout (probably because of CF).
You can change the timeout from 30 seconds to something lower, but you shouldn't lower it too much.
"Options->Connections->Connection timeout (seconds)"

Alternatively you can just disable mangago if you don't use the cf workaround.
Just order the list by website, select all mangago entries and rightclick -> disable it.

**Comment by leoteesh** [comment]
Thanks for your reply...
i have tried the cf workaround but unfortunately that didn't work. :( 
don't really want to disable mangago as some of the favorites i have are only available from there.

**Comment by SDXC** [comment]
The CF workaround is a bit tricky sometimes. I'm working on a more elegant way for CF at the moment.

Disabling MangaGo would be temporary, you can always re-enable it again.
Or you can get the workaround to work, so you can retry it of course.

Right now, MangaDex is having it's regular DDoS again, so I wouldn't try to do it right now.

**Comment by Tmp341** [comment]
Mangago was the main problem FMD had, back in the days. I've stopped using it years ago. But this CF is spreading like a flu.

**Comment by azraei97** [comment]
Due to security protection for website have CloudFlare like mangadex and mangago, please use make custom setting for cookies and useragent in Options > Websites > Advance. Cookies and useragent can be get by press F12 in your browser.
