### ISSUE TITLE
Global Search for mangas

### ISSUE THREAD

**Issue by sukhijapiyush** [fmd-project-team/FMD#1114]
It will be great if we can search across selected sources to compare chapter number and select the one which is good for us.

**Comment by Tmp341** [comment]
> 
> FMD is mainly download based, it's purpose is making downloads easy, not searching through all sites. But it is up to developers to decide.

I've stated this before (even riderkick said the same long ago), in the issue Slasar41 pointed. FMD is a downloader, not a cross checker. Iirc, riderkick never wanted to add ``"add/update database"`` since that needs a lot of attention, dedication. Websites changes their structer almost daily, and with the new Cloudflare rise, you will have a lot of problem while checking between sites.

But as i said, it is up to developers. You can ask that on more active repo [FMD2](https://github.com/dazedcat19/FMD2).
