### ISSUE TITLE
Some titles or chapters are missing [MangaRock]

### ISSUE THREAD

**Issue by Sloth671** [fmd-project-team/FMD#212]
So I'm not exactly sure why this is happening. That's the only manga that is being registered as N/A on the manga list, but the link works perfectly fine. Any help?

![Capture](https://user-images.githubusercontent.com/50787856/58573638-82e5c880-8281-11e9-9def-924ee97302bd.PNG)

**Comment by Tmp341** [comment]
Please don't close issues unless it is fixed.

**Comment by Tmp341** [comment]
Tried it on my end, and i got the manga list on mangarock.

**Comment by SDXC** [comment]
This is a lightweight Region Lock.
Currently MangaRock automatically detects or assumes you country and if it's set to "United States" the api will block because of "Manga is licensed". If you set another country manually in the url, you can override that behavoir (for example if you set "China").

I added a new option in FMD, so you can set a country of your choice. Default is United States though.

![MangaRock-Country](https://user-images.githubusercontent.com/5290260/59152073-97724f80-8a3d-11e9-8b1d-841f20a13f8a.png)

**Comment by SDXC** [comment]
FMD 0.9.165.0 has been released.
The default country has been set to China which should let you get most of the titles.

**Comment by sadeghp88** [comment]
hello
it still doesn't work
https://mangarock.com/manga/mrs-serie-264761
