### ISSUE TITLE
Can't download manga [TumangaOnline]

### ISSUE THREAD

**Issue by akir42019** [fmd-project-team/FMD#227]
The chapter download does not work at https://tmofans.com/

**Comment by rs3mk** [comment]
yes, not work.

**Comment by ralvarador** [comment]
for the last two days, tumangaonline is failing again. It is not about cloudflare issue because FMD detects the new chapters, also it is possible check and get the information from the title, but when downloading it fails.
It seems be a "Scripting" issue.

![image](https://user-images.githubusercontent.com/30580377/59142307-da6eed00-8981-11e9-95ca-b1affc0b6909.png)

**Comment by SDXC** [comment]
Chapter download should be fixed now. CF doesn't even seem to be active anymore.

**Comment by lordzidiousback** [comment]
again whe cant download from tmosfan i do everyting posible to treat to work but dont maybe is de page  have cloudflare again

**Comment by ralvarador** [comment]
Yesterday, tmo had CF active. The CF cookie workaround worked for me.
Now, it seems not being active, check out...

**Comment by lordzidiousback** [comment]
@ralvarador can you sendme the config for cf cookie workaround worked for you todat again tmofan dont work and i dont now do the workaround
