### ISSUE TITLE
Some Antivirus detects cf_bypass as malware

### ISSUE THREAD

**Issue by ooberallen** [fmd-project-team/FMD#263]
Just updated to 0.9.165.0 from 0.9.164 via the app, as soon as the update finished I got a popup from my virus scanner saying that cf_bypass.exe was infected with Troj.Win32.TRX.XXPE50F13008.  software said it was cleaned but still a little concerned.

**Comment by SDXC** [comment]
That's a false alarm.

When using cf_bypass, FMD calls it for getting cookie information from different websites. So an AV may see that as the characteristics of a trojan malware.

Which AV do you have, btw.?

**Comment by Tmp341** [comment]
That's weird : 

[Virustotal](https://www.virustotal.com/gui/file/fbe65b6d84fd50917876f0be40d7fb8f3d14f9e2afc246bc0d99c041f4f56751/detection)

**Comment by ooberallen** [comment]
trend micro, downloading manga at work lol.

**Comment by Josexv1** [comment]
Can confirm Avast and Avira detects as some default Trojan, because it has python's code embedded.

That's a common practice for malware embedded into a legitimate file, maybe it's a **false positive** but it's still detected because of that.

Btw: @Tmp341 this is a scan of my file: [VirusTotal](https://www.virustotal.com/gui/file/93b4c85ecc932ce28c58619819cc78c0eff15d7aaccd1232317624b968201c6d/details) with 8/64 detections, one as a potential **MS17-010 exploit**, which is **Eternalblue**.

Will dig into this and post a follow up, while i run FMD in custom way i can't confirm anything until i test the download in a VM.

**Comment by Josexv1** [comment]
Update. I checked the file with a few tools and got some results.

The file @Tmp341 and i linked are diferent, in size and ofc hashes,
The file i linked was updated with the auto-update feature included in FMD. Checking my logs, i couldn't get a tampered file because i heavily control my traffic because i usually work with dangerous files.

I downloaded again the whole project in releases and the hashes for **cf_bypass.exe** is: **531c3f7e5bbbed7b66ad2183a299dfdcfdbc720c**  The same as the file downloaded in Auto-updater.

The SHA-1 of the file linked by @Tmp341 was: efb2c9e347d2bc04f705cc032d487207d1ba5879.

The sizes also mismatch, the file in releases having less bytes, and the date created had 4 minutes of diference.
![cf_bypass](https://user-images.githubusercontent.com/12077848/59539475-cd974f80-8ed3-11e9-966a-a24aad52756a.png)
![cf_clean](https://user-images.githubusercontent.com/12077848/59539479-cf611300-8ed3-11e9-9991-f539abf38cfe.png)


The analysis
---

While i did not found something nasty the file indeed behave as some common malware. creating and deleting temp files, using a lot of APIs and uses some mutex and other obfuscation to hide it's content (anti-reversing).

Some of the files created/modified/deleted are: 
```
C:\93b4c85ecc932ce28c58619819cc78c0eff15d7aaccd1232317624b968201c6d
C:\DOCUME~1\<USER>~1\LOCALS~1\Temp\_MEI6082\VCRUNTIME140.dll
C:\DOCUME~1\<USER>~1\LOCALS~1\Temp\_MEI6082\_bz2.pyd
C:\DOCUME~1\<USER>~1\LOCALS~1\Temp\_MEI6082\_hashlib.pyd
C:\DOCUME~1\<USER>~1\LOCALS~1\Temp\_MEI6082\_lzma.pyd
C:\DOCUME~1\<USER>~1\LOCALS~1\Temp\_MEI6082\_queue.pyd
C:\DOCUME~1\<USER>~1\LOCALS~1\Temp\_MEI6082\api-ms-win-crt-locale-l1-1-0.dll
C:\DOCUME~1\<USER>~1\LOCALS~1\Temp\_MEI6082\cf_bypass.exe.manifest
C:\DOCUME~1\<USER>~1\LOCALS~1\Temp\_MEI6082\libcrypto-1_1.dll
C:\DOCUME~1\<USER>~1\LOCALS~1\Temp\_MEI6082\libssl-1_1.dll
```
The first one being `cf_bypass.exe`
NOTE: The files are **NOT** being downloaded, they're extracted from the .EXE, and all of the files are **CLEAN** according to a few analysis and AV scans.

The files are downloaded in `CurrentDirectory` , `\Temp\_MEIXXX\` , `%WinDir%` and `%System%` 

The process creates a child process `cf_bypass.exe` and grabs a bunch of info of the PC, like the registry key of the name of the PC and the GUID. 

The behaviour is similar to a Hacking Tool called: [LaZagne](https://github.com/AlessandroZ/LaZagne) according to a report.

There are a few strings called: "cmd=" which is probably part of the cf_scraper (if they use that library), anyways is common.

![cf_clean](https://www.hybrid-analysis.com/file-inline/5d03f8f9028838748afc4049/screenshot/screen_1.png))

The file does NOT make any weird *TCP/UDP* connection, while i got a few localhost connections that's a common error.


Reports URL:
---
https://any.run/report/93b4c85ecc932ce28c58619819cc78c0eff15d7aaccd1232317624b968201c6d/f266c5d8-9161-4157-bbed-452553b1535c

https://www.hybrid-analysis.com/sample/93b4c85ecc932ce28c58619819cc78c0eff15d7aaccd1232317624b968201c6d
_The test was made only with `cf_bypass.exe` file, and not with the whole FMD project running._

**Comment by ChocolateOtaku** [comment]
There may be 32 Bit and 64 Bit which would explain different hashes.
If you want to be 100% sure grab all the source code, check for malicious code and build the application yourself.
Unfortunately the python stuff seems to be not open sourced and therefore you can not be sure it is safe.

**Comment by SDXC** [comment]
cf_bypass using Python was never meant to be a permanent solution, that's why the source for that won't be a part of the FMD repo. But here you can grab the currently used code for cf_bypass including the customized cfscraper script if you're interested:

[cf_bypass [source].zip](https://github.com/fmd-project-team/FMD/files/3292442/cf_bypass.source.zip)

**Comment by Josexv1** [comment]
@ChocolateOtaku Indeed they're from different arch. That explains why the files missmatchs, but no why the x64 is detected as malware. I pointed in my first comment that pyinstaller is commonly used by malware factories or binders, that's why many exe's are **being flagged** as false positives. Mixed with the registry and create and delete temp files, spawn and kill of child process, that behavior is really common to most malware. 

I tested the whole project and it works as intended, You can utilize Process Monitor to check what the `cf_bypass.exe` does and or use a free sandbox to check it's **safe**.
