### ISSUE TITLE
Chapter download doesn't work [ReadMangaToday]

### ISSUE THREAD

**Issue by jillybeans** [fmd-project-team/FMD#286]
the issue I'm having is nothing is being downloaded from that site, no matter which one I'm downloading. not sure if it's only my end.

**Comment by AbidZakaria** [comment]
give me one problematic link

**Comment by jillybeans** [comment]
https://www.readmng.com/my-wife-is-a-demon-queen

https://www.readmng.com/one-punch-man

 I gave 2 just incase, and sorry first time posting an issue

**Comment by Tmp341** [comment]
Website has CF it seems and cf_bypass probably couldn't get cookies (my cookie tab is empty) even though i got chapter list.

**Comment by AbidZakaria** [comment]
there is a change to the site
so you can't take the manga,
does this only happen that manga or all manga?

**Comment by jillybeans** [comment]
all manga so far I can tell

**Comment by AbidZakaria** [comment]
I will fix it

**Comment by AbidZakaria** [comment]
@Tmp341 readmangatoday not using Cloudflare on that site

**Comment by Tmp341** [comment]
But i get : 

> __cfduid=xxxxxxxxxxxxxxxxxxx
ci_session=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by SDXC** [comment]
ReadMangaToday uses FunManga as image hoster. FunManga has CF enabled and that's why the downloads fail because cf_bypass doesn't try to get cookies from FunManga.

For such cases I implemented the advanced website setting "BypassURL":

![BypassURL](https://user-images.githubusercontent.com/5290260/59851153-3109fd00-936c-11e9-8a86-6ceff2c18b6c.png)

You have to simply get the url from on of the chapter images and paste it like in the screenshot.
When cf_bypass runs the next time, it will get the CF cookies from FunManga instead of ReadMangaToday and the download will work.

After setting the BypassURL just apply and restart FMD. Also make sure you don't have any cf_clearance cookie and user agent set anywhere for ReadMangaToday.

**Comment by ratbunuts** [comment]
Why does the useragent always comes back everytime i delete it and apply it?

**Comment by SDXC** [comment]
@ratbunuts Everytime FMD loads a website (update manga list, viewing manga info, checking for chapter updates or downloading) the cf_bypass runs if FMD detects Cloudflare on a website.

cf_bypass automatically sets the user agent and cookies in the advanced settings.
This is correct. What my screenshot was meant for you to show is that you have to set the BypassURL, Apply and then restart FMD (this will clear the cookies and user agent in CloudflareBypass).

You then have to simply load a manga info or check for chapter updates and cf_bypass will now get the cookies and user agent from calling the BypassURL, which will result in the downloads working again.
