### ISSUE TITLE
Updater size increase

### ISSUE THREAD

**Issue by ChocolateOtaku** [fmd-project-team/FMD#4]
It seems the `updater.exe` size increased by almost 15 times.
Was this intentional?

**Comment by SDXC** [comment]
Yes, there is a flag in the Lazarus project, that, if disabled, increases the size but also the performance. It may be more on the micro optimization part. Also I have a newer version of Lazarus and the base libraries, so it's possible that it also increased because of that.

I decided to do that, because these kind of file sizes don't really hurt.
And the package archives (7z) are actually smaller than the old ones.

**Comment by ChocolateOtaku** [comment]
Closed as answered

**Comment by SDXC** [comment]
I was actually using the wrong udater project. I didn't notice, that FMD moved to the slim updater. That was also the reason of the file increase.
