### ISSUE TITLE
Can't Download Chapters [OneShotScans]

### ISSUE THREAD

**Issue by Velgen** [fmd-project-team/FMD#403]
Downloads do not appear to work at all for OneShotScans. Tried messing about with manually adding in the cookie data/CF cookies still no luck.

**Comment by SDXC** [comment]
You have to do the manual workaround by visiting the website and opening up a random chapter. You will then get the Cloudflare page before you can read the chapter. You need to do the workaround with the chapter page instead of the main page.

cf_bypass has problems with OneShotScans and the BypassURL workaround doesn't work.

**Comment by Velgen** [comment]
Okay ya that is what I did I am a derp and it appears for some reason my user agent didn't properly copy paste in. Thought I had checked everything multiple times before posting, but it appears I still missed something.

**Comment by SDXC** [comment]
Next version of FMD will have a fix so at least the BypassURL will work.
