### ISSUE TITLE
Manga catalog [Question]

### ISSUE THREAD

**Issue by djgerman10** [fmd-project-team/FMD#441]
**This is just a question, I don't know if I should do it here**

Is there a cataloger for Manga?
as the movie and anime cataloger (tinyMediaManager)

**Comment by SDXC** [comment]
That is really a question that doesn't belong here. If you have joined our Discord server you can ask there.

The issues here are only meant for FMD.

And to give you an answer. I don't know of any other management tools for manga. I read about Calibre, but that is mostly for general purposes I guess. Currently I'm writing an application for myself because I didn't like other solutions. Maybe I'll release it at some point, but not yet.

**Comment by djgerman10** [comment]
### Thanks a lot for the suggestion.

If you decide to ever release your program, I will be reviewing it

**thank you.**

**Comment by SDXC** [comment]
Here's a sneak peek of my tool:
https://imgur.com/gallery/xJ67m0C

**Comment by djgerman10** [comment]
great is a great complement to FMD

 I have more than 500 downloaded Mangas and some I forget what it was, this is very useful for all FMD users


sorry for my English

**Comment by djgerman10** [comment]
I found an interesting app but it is outdated

[https://sourceforge.net/projects/mangaddict/](https://sourceforge.net/projects/mangaddict/)
