### ISSUE TITLE
Renaming of ticket titles

### ISSUE THREAD

**Issue by ChocolateOtaku** [fmd-project-team/FMD#450]
I would really appreciate if the title in the tickets would not be renamed because of personal preference. Seriously almost **EVERY** ticket here got its title changed, **this is kinda rude** to the users that take the time to report bugs and may imply their chosen title is inferior.

Furthermore the title is used to locate the ticket, if someone created a ticket and the title get changed it may become more difficult to find the ticket again in case you forgot the number.

That said i suggest only to change the title if it is really necessary for misleading contextual reasons and not for visual appearance.

----

Example: `add site [mangahosted] `
Renamed to: `Add support for website [MangaHosted]`

There was no reason at all to rename this, the content was perfectly fine. It was just renamed because the developers dislike the format and suppose their new title is better and superior than the one chosen by the author.

**Comment by SDXC** [comment]
This has nothing to do with rudeness. It may be a personal preference but it also helps me with the ticket management which becomes easier for me if the issues follow some kind of naming guideline. Users tend to not notice, forget or simply ignore guidelines and such, which is why I decided to do the renaming when I actually get to look at the issue. I think always reminding users about some guidelines will get more problems than just doing it myself.

The issuers have many ways to keep their tickets in check by using the notification mails or by explicitly searching for their issues on Github. I may have Labels to categorize, but sometimes it's still better using the cleaned up titles when I look through the list.

I don't plan on changing my approach at handling the issues for now, as I'm currently the only one who has to manage them (except Tmp341 who helps me with that).

With that I'll also close this issue.

**Comment by Tmp341** [comment]
It sounds like rudeness but i even see some people writes whole problem on title, which is hard for authors to understand what is going on and classify them regarding the issue. As SDXC said, i offered him help so i can category issues, so he can work on them with priorities. We all have personal life, so it helps him to some degree i think. He changes titles, so he can manage problems like ``Download doesnt work [xxxxxxx]``. We can also make labels for sites so he can filter issues, but there are hundreds of sites out there and we can't crate that much labels, as labels are mainly used for stating problems. There is only option for us: changing title for our benefits, so we can (actually only SDXC and some coders) can understand what happened.

If people feels offended just by some changes, we will make progress more slower while trying to understand and managing the issue.

**Comment by ChocolateOtaku** [comment]
Yes i understand that:

- you get tons of tickets everyday so managing the title is the way to go
- managing tickets by title is so popular that almost any other project on github is doing this
- users should spend alot of time selecting a title, because it will be changed to something else anyway

However, do as you please.
In case i report a bug anytime, i will not bother to enter a title at all, because it will be automatically done for me...

**Comment by SDXC** [comment]
Look, you have the option to fork the project and do your own thing at any time.

**Comment by ChocolateOtaku** [comment]
I take your advise (bet you didn't expect this)
Diversity might be good...
https://github.com/ChocolateOtaku/FMD2

**Comment by SDXC** [comment]
Mmmh. To be honest I actually did expect this somehow. But maybe you could implement the anime downloads you wanted now. Would be a good oppurtunity.

I really don't care about competition and user counts, I mean it's just a fork. I'm happy if people use my fork and if I'm able to help them, but first and foremost I'm doing this for myself. Either I get less work to do or nothing really changes, so it can only affect me positively.

So, happy coding I guess?

**Comment by ChocolateOtaku** [comment]
Thanks, will do my best to make this a community focused project which is not aimed for my personal desires. Guess i will start with something simple first as i only have little C# experience and Pascal is new for me
