### ISSUE TITLE
Favorites: Check for new chapters

### ISSUE THREAD

**Issue by molitar** [fmd-project-team/FMD#483]
When it runs through the auto timed check for new chapters it will time out and fail on sites that the Cloudflare has expired like Kissmanga.  If I stop the check for new chapters and then right click on a timed out one like kissmanga and check for new chapter manually it will work then I can go ahead and press the check for all chapters button.
 
So it seems the button/scheduled check for new chapters does not use the Cloudflare Bypass automatically.

**Comment by SDXC** [comment]
The mechanism behind cf_bypass has problems detecting when the cookies have been expired. This has been known ever since I introduced cf_bypass and is also part of the planned optimizations: https://github.com/fmd-project-team/FMD/issues/233

This is not directly a bug but a feature that has not been implemented yet.

I will close this issue as a duplicate.

For now I can only advise you to restart FMD occassionally so that the cookies are being renewed on the next check.
