### ISSUE TITLE
Number of chapters available and completion status is not working unless the title is manually clicked

### ISSUE THREAD

**Issue by komaedalove** [fmd-project-team/FMD#506]
All of my databases are up to date and I update them frequently. The new titles appear in the manga info list properly. However, for some of the titles, the chapter number next to title and the completion status aren't updated properly. For example, a completed manga with 20 chapters will show up as an ongoing manga with 0 chapters. After clicking the title and viewing "manga info" in-app, the completion status and chapter number updates correctly as it is on the online site.

The wrong chapter number happens on most websites (I'm using Batoto, MangaDex, MangaPark, NineManga and more)
The wrong completion status doesn't happen as often, but I noticed it on MangaDex, MangaFox, Mangahere, Mangaherefun, Mangatown.

Sometimes the title is highlighted green "complete" but shows (0) chapters next to the title, despite chapters being available. This updates when clicking "manga info" to the correct chapters/completion are shown on the website.

**Comment by SDXC** [comment]
This is an expected behavior of these database files.

As they are static, FMD doesn't update the list everytime so the chapter count and manga status will be the same like it was at the time the list was created. To get a more updated list you will have to delete the database file and update the manga list yourself.

Updating the manga list when you already have an existing database file doesn't update the already listed mangas, it only adds new ones. This is also an expected behavior so the website hits are not too high because of these list updates.

In some cases it's also possible that the list updates get timeouts on some mangas, which is likely to happen on thousands of titles to check, and will be listed as ongoing titles with 0 chapters. But it's also possible, especially in case of MangaDex, that chapters were added way later than the manga pages itself were created. That would also result in a ongoing or complete manga with 0 chapters.

Regarding the manga status on MangaDex: The API only exposes the status in the country of origin, so many titles will be marked as completed, even though they aren't.

**Comment by komaedalove** [comment]
Thank you for your answer! I'll try updating the databases from scratch.
