### ISSUE TITLE
Chapter check freezes in 0.9.167.1

### ISSUE THREAD

**Issue by Renvix** [fmd-project-team/FMD#511]
After the program is opened, FMD looks normal by starting from the favorite check, but after the favorite check is finished FMD does not start downloading the latest chapter and continues to say "checking ..." on the check update button, after that anything done like exiting fmd will end freeze or not responding
![Untitled](https://user-images.githubusercontent.com/29302760/65391127-ca8fe300-dd8f-11e9-833a-dc1498cf62da.jpg)

**Comment by Tmp341** [comment]
On which manga it stops? Which site specifically?

**Comment by SDXC** [comment]
Does this always happen or only occassionally?

**Comment by muhamadrid** [comment]
I get similar issue. FMD freeze after finished checking favourites. Its happen everytime.

**Comment by pclkpg581** [comment]
I also have this issue. I have a long list, and it's random when it freezes during the hourly favorites update. I've also noticed that FMD periodically hangs (since the update), which typically lead into the program freeze.  It always happens. The last two program runs of this happening managed to log:

ERROR: Access violation: https://mangadex.org/api/manga/21498 (1st instance)
ERROR: Access violation: https://mangadex.org/api/manga/41727 (following instance)

I can't be certain this error occurs every time this happened before. The first error was logged after ~4 hours, the next after ~11 hours.
