### ISSUE TITLE
Wont download pages [MangaKakalot]

### ISSUE THREAD

**Issue by Thrieze** [fmd-project-team/FMD#591]
Looks like everything else is working, cf bypass, can list chapters, but downloading chapters just shows 1/1 and errors out.

**Comment by Slasar41** [comment]
I can download just fine.
![image](https://user-images.githubusercontent.com/28888646/67979747-7f4ed700-fc4f-11e9-854e-8839b3b45821.png)

**Comment by Thrieze** [comment]
Very strange, I can read it on their site just fine, but downloading doesnt work, I even tried the same one you did, it shows the number of pages but fails.

**Comment by Tmp341** [comment]
It forwarded me to ``https://manganelo.com/chapter/kobayashisan_chi_no_maid_dragon/chapter_89`` on mangakakalot.

**Comment by Slasar41** [comment]
If I download it from MangaKakalot website, it'll fail.
If I download it from MangaNelo website, it'll download fine.
![image](https://user-images.githubusercontent.com/28888646/68047613-64dd3200-fd11-11e9-8dd6-5092c86f1f5a.png)
Looks like some titles on MK redirect to MN and it's confuse FMD.

**Comment by Thrieze** [comment]
Huh interesting, I did not notice. Thanks. They definitely didn't redirect in the past when I first bookmarked them.

**Comment by traitorAIZEN** [comment]
so you're gonna just leave that error there?

**Comment by Tmp341** [comment]
Leave which error? Only problem here is `mangakakalot` is redirecting some of it's mangas to `manganelo`. That is not a FMD problem.

**Comment by traitorAIZEN** [comment]
Is there so way  that fmd can automate this? Like if fails fetching from mangakakalot, instead of showing a "failed" status, it'd try fetching frommanganelo next. I know there's the manual method mentioned above and fixing this is just for convenience sake. But if magakakalot keeps transferring more and more titles to manganelo in the future, then it'd be a irritating to be always checking both sites for the same content.

**Comment by SDXC** [comment]
Sadly it's not that easy to break down FMDs source code to work like that. FMD has many design issues and this is one of these issues. Because of the more or less linear and isolated way the website modules are implemented, it would be too much effort to introduce some kind of cross-site support. Rewriting FMD in a modern language would probably be faster and cleaner....

I also see two possible scenarios with MangaKakalot:
* It moves completely to MangaNelo at some point.
* It regains the content on its own site again. This happened with some other websites too. They probably didn't have much space left and just linked content until they upgraded or so. Just guessing on the reason though.

Maybe it's best to move to MangaNelo completely if they have the same content available.
