### ISSUE TITLE
Can't Download Some Manga [Mangarock]

### ISSUE THREAD

**Issue by andre4846** [fmd-project-team/FMD#642]
here list my manga favorite can't open site/manga info or download but can view on android app mangarock definitive
A Harem in the Fantasy World Dungeon  https://mangarock.com/manga/mrs-serie-100058260/
Assasin's Pride  https://mangarock.com/manga/mrs-serie-100096263
Bloom Into You https://mangarock.com/manga/mrs-serie-276604

**Comment by Tmp341** [comment]
Well, Mangarock closed it's doors to outside world. They've written that they will remove content slowly. So, if you can't reach a content without it's app (like from browser),  there is nothing we can do about it from here.

**Comment by SDXC** [comment]
if you go to "Options"->"Websites"->"Options"->"MangaRock" you can set the country to "USA" instead of "China" and then you'll be able to see the titles. But some other titles might not be visible because of that. so keep that in mind. You can try different countries, until you find the one that works best.
