### ISSUE TITLE
Can't download [MangaNelo]

### ISSUE THREAD

**Issue by PhantoManresa** [fmd-project-team/FMD#691]
It seems that MangaNelo site got updated and now I can't download anything from it.

**Comment by spamtaztik** [comment]
Just to clarify, nelo did change the address for -some- manga (e.g. from https://manganelo.com/manga/fenglin_tianxia to https://manganelo.com/manga/jqae5201574492597), but there are still some manga that retain the old address (like https://manganelo.com/manga/arslan_senki_arakawa_hiromu).

The problem is, starting today -all- manga from nelo can't be downloaded (new address format and old address format). The address can still be opened through browser but not through FMD, not even the "manga info" page. So it's not really a "site changed" issue, but more like a "need lua update" one, perhaps?

**Comment by SDXC** [comment]
Fixed thanks to @Slasar41 
Issue will be closed. If you still have problems you can just re-open the issue.
