### ISSUE TITLE
Not working 1.2.0.0

### ISSUE THREAD

**Issue by akir42019** [fmd-project-team/FMD#816]
No website that uses updated lua module works,
lua modules disappeared from the interface after the update.

**Comment by Black-Dalek** [comment]
saem issue, also hentai cafe dissapeared from h sites list

**Comment by ImportTaste** [comment]
I'm having the same issue...

**Comment by Tmp341** [comment]
[lua.zip](https://github.com/fmd-project-team/FMD/files/4238907/lua.zip)

Put this file inside ``config`` folder.

**Comment by ImportTaste** [comment]
@Tmp341 The workaround worked, but I updated to 1.2.1.0 today and now the modules are gone _again_.

**Comment by muto4013** [comment]
you are lucky that only the modules list has gone, after update to 1.2.2.0 i had to re-install FMD because lot's of settings where reset to default, cookies where gone and fmd was extreme unstable. 
I still have some problems with mangadex and lhtranslation, checking the fav's gave every few entry's a red mark. (it could be a problem with their sites, don't know at the moment).

**Comment by ImportTaste** [comment]
Unfortunately I lost all my favorites as well.

**Comment by dazedcat19** [comment]
> Modules are back, but unfortunately I lost all my favorites as well.

There's should be a backup folder where you can find your backup in a week. Just extract one of them.

**Comment by Tmp341** [comment]
@muto4013 @ImportTaste After [v1.1.0.0](https://github.com/fmd-project-team/FMD/releases/tag/1.1.0.0), FMD now contains backup feature, which backups your ``config`` and ``works`` folders. You can extract what has been lost, like ``favorites.db`` or ``config.ini``
