### ISSUE TITLE
[Webtoon En] Download limited to only the lastest 10 columns

### ISSUE THREAD

**Issue by JokoeSukri** [fmd-project-team/FMD#833]
I found this problem only with English Webtoon,
![Screenshot_31](https://user-images.githubusercontent.com/32964994/75352872-c8f1ba80-58ed-11ea-9ed2-2c7e202018f1.jpg)

While Other Webtoon region is perfectly normal
![Screenshot_32](https://user-images.githubusercontent.com/32964994/75353064-166e2780-58ee-11ea-98c8-a5eb43c27c49.jpg)

**Comment by ahmadi3d** [comment]
You can close this, as i mentioned in https://github.com/fmd-project-team/FMD/issues/850, the problem was the old database which didn't reflect the latest URL changes in the site, for example in your case Unordinary is now in super-hero gener 
https://www.webtoons.com/en/super-hero/unordinary/list?title_no=679
Not the fantasty gener
So this confirms what i said in #850 and this issue can be closed.

**Comment by Tmp341** [comment]
I've updated server database for Webtoons. Delete yours and redownload it.

**Comment by JokoeSukri** [comment]
Ok, fix thans
