### ISSUE TITLE
desire to walk ninemanga ES

### ISSUE THREAD

**Issue by djgerman10** [fmd-project-team/FMD#861]
desire to walk ninemanga ES
![l](https://user-images.githubusercontent.com/48584512/77183095-91b99800-6aac-11ea-9feb-efd0d493997b.png)

**Comment by Slasar41** [comment]
Works fine on my side.
![image](https://user-images.githubusercontent.com/28888646/77196038-3374cf80-6b15-11ea-8b5f-473a0e8deb4a.png)

**Comment by djgerman10** [comment]
if i fixed it, the ninemangas.lua was corrupted

thanks for commenting thanks to that I was able to find the solution.

**Comment by djgerman10** [comment]
stopped walking again

**Comment by djgerman10** [comment]
ninemangaES I'm not in Hakuneko either

**Comment by ZeroCool940711** [comment]
NineMangaES doesn't work anymore, it seems like the Spanish version of the website is having some internal error or something, alll the other languages version of NineManga works but not the spanish version, for example if you go to the manga for `The Gamer` on the english version that is on [this link](http://www.ninemanga.com/manga/THE+GAMER.html) the site will work but on the spanish version on [this link](http://es.ninemanga.com/manga/The%20Gamer.html) it doesnt work. Also as I said on my comment on issue #819 not even before downloads were working correctly, most downloads had missing files, about 9 out of 10 downloads had missing images for each chapter, probably because before NineMangaES was redirecting to another website which was weird as the site doesnt seem to be related to NineManga it was called [GardenManage.com](https://www.gardenmanage.com), also even when I try to force FMD to check for new chapters or download a specific chapter it still wasnt downloading and was counting everything as if it was up to date, I think its because some chapters on the spanish version have different naming format, for example some chapters might have a format like this `Manga Name Capítulo 110` while other have a format like this `Manga Name Ch. 108`, would be nice to have an option to force all mangas to have the same chapter format, and yes I know there is a `Renaming` section on the `Save To` tab under `Options` but the `Chapter Name` field only have a handful of options and most of them use whatever the website gives us so if you try to use something like `%CHAPTER%` it will just copy the chapter name as it is on the site, would be nice to have an option to remove or replace some text from the name.

**Comment by djgerman10** [comment]
he walked again

![j](https://user-images.githubusercontent.com/48584512/77290792-ae77ea80-6cbb-11ea-8f9e-ab9fc0ff112b.png)

**Comment by megumixd** [comment]
well is dead again :c i cant dowload again
