### ISSUE TITLE
FMD apparently abandoned fans of Spanish manga

### ISSUE THREAD

**Issue by djgerman10** [fmd-project-team/FMD#866]
FMD apparently abandoned fans of Spanish manga, because there is none

_Is it time to move to Hakuneko?_

**Comment by Tmp341** [comment]
Fmd developers are busy irl. And like you can guess, this was a long gone project before. And, FMD is based on Pascal and it is hard to fix websites, which javascript encoding or scrambling etc. And Spanish websites change their coding daily mostly, since it is hard to fix it for us who is here now.

In short, you should use the app fits you most.
