### ISSUE TITLE
Cannot download certain updates on LHScans

### ISSUE THREAD

**Issue by TienVer** [fmd-project-team/FMD#883]
So...a couple days ago, there was some curious hiccup on LHScans (or as we all know it, Loveheaven.net). Certain titles completely disappeared from the listings and word in the side chat let it float that there was a cleanup of the more adult or risqué series (which didn't make sense as titles like DeadTube, which are hardly SFW, were still alive).

Those MIA series just came back today, but now it seems we just can't DL them anymore.

Here are a few examples:
Tono Kanri o Shite Miyou
Seiken Gakuin no Maken Tsukai
Nidoume no Jinsei wo Isekai de
Tenkuu no Shiro o Moratta no de Isekai de Tanoshiku Asobitai

Try as I might, I can't download their chapters - not even the recruitment page that is usually spared as with the last LHscans-related issue.

Note that this problem is NOT endemic to all new updates. For example, I was able to DL "Aa Shukatsu no Megami-sama Tsu" and "Gensou Gourmet" without a hitch today.

Did something change with the website? Did they add some mature/adult filter?

EDIT: should change the thread title to "cannot download certain series (..)" since it seems the problem is tied to those titles that temporarily went offline rather than their latest chapters.

**Comment by micederX** [comment]
If you try to access them directly in a browser, you'll get a message saying you need to log in to account to access things tagged 'ecchi'.

For now, you can use this method (https://github.com/fmd-project-team/FMD/wiki/CF-Workaround:-LHTranslation) to access and download them (until the site changes again, or FMD staff adds an account option for LHscans).
Just remember to log in to an account on the site (loveheaven.net) before getting the cookies, and apply the changes to LHScans instead of LHTranslations in FMD.

**Comment by TienVer** [comment]
Huh. I thought the latest LHScans module update bypassed the login restriction. I'll reactivate the custom settings, then.

Thanks.
