### ISSUE TITLE
Webtoons site doesn't download.

### ISSUE THREAD

**Issue by Reyeselda95** [fmd-project-team/FMD#929]
The webtoons site detects new chapters but when downloading always gets errors.
It also happens that when loading a page of the manga info only shows the last 10 chapters instead of everything.
The last thing I comment happens from long ago, so I don't know if it's something that can be fixed or not.
Thank you beforehand ^^

**Comment by Tmp341** [comment]
That's weird, because i can download from webtoons just fine. 

Check #905.

**Comment by Reyeselda95** [comment]
It downloads using the cookie, but still, with series like, the gamer, lumine, S.I.D., etc, it only shows the last 10 chapters, but for others like XINK3R it shows everything...
![imagen](https://user-images.githubusercontent.com/22152673/79695423-126bdf80-8277-11ea-8db1-b7be3fbf9de6.png)
![imagen](https://user-images.githubusercontent.com/22152673/79695443-2dd6ea80-8277-11ea-958c-07cff20d97b4.png)
![imagen](https://user-images.githubusercontent.com/22152673/79695468-4cd57c80-8277-11ea-8124-4d1e21bb5da8.png)

**Comment by IgnatiusC** [comment]
Getting the same problem. Adding agegatepass to cookie fixes downloading but the info tab is only grabbing the first page of chapters. I assume it's the same problem since clicking page 2 on the site brings up the age gate.

**Comment by Uroth** [comment]
I am getting the same issue about only seeing the latest chapters of some of the series.

The Gamer has this issue: 
![image](https://user-images.githubusercontent.com/11475365/80371735-a7cc2c80-8892-11ea-8a9e-59b5c4117de7.png)

But Tower of God does not..
![image](https://user-images.githubusercontent.com/11475365/80371836-d5b17100-8892-11ea-9433-c76d5f818942.png)


Is there a way to fix this? I am missing a few chapters due to failed or incomplete downloads but they are to far in the past for me to get now.
