### ISSUE TITLE
Can't download lua folder

### ISSUE THREAD

**Issue by Weeggllss** [fmd-project-team/FMD#938]
After downloading 1.3.3.0, I don't see many sites in the interface. The lua folder is missing and the JSON files associated with lua in the config folder are missing. The modules tab in the program is empty. My last version was 0.9.158.0 from riderkick/FMD.
  (English is not my native language. I use Google translate)
   После скачивания 1.3.3.0 я не вижу многих сайтов в интерфейсе. Папка lua отсутствует и файлы json связанные с lua в папке config отсутствуют. Вкладка "модули" в программе пуста. Моя последняя версия была 0.9.158.0 от riderkick/FMD.

**Comment by Tmp341** [comment]
FMD changed it's module structre after 0.9.158.0 riderkick version. Make a backup, dele all files except these (important ones are bold) :

* config\config.ini -> Your personal settings (keeps save here info etc)
* config\modules.json -> Your personal entries for sites (User Agent etc)
* data\ -> Manga sites' manga databases. If you've updated them, keep them. (But read the note below)
* **works\downloadedchapters.db** -> As the name says, downloaded (but not favorited) manga chapters. If deleted, fmd might find them again.
* **works\downloads.db** -> Active Download list, downloaded but not deleted or haven't started. If deleted, have to add again.
* **works\favorites.db** -> Favorites. Keeps favorite mangas' links etc.

Don't backup config/base.ini, because you need the base.ini from this fork to get updates, etc.!

After backing up these files, install FMD again.

Note for data files: If a manga has changed it's manga pages (from a.com/manga to a.com/mangas/manga for example) your favorites and/or manga database for that site might not work.

--------------------------------------------------------
Using Google Translate for you/Использование Google Translate для вас:

FMD изменил структуру своего модуля после версии riderkick 0.9.158.0. Сделайте резервную копию, удалите все файлы, кроме этих (важные выделены жирным шрифтом):

* config \\ config.ini - Ваши личные настройки (сохраняйте здесь информацию и т. д.)
* config \\ modules.json - Ваши личные записи для сайтов (User Agent и т. д.)
* data \\ - базы данных манга сайтов манга. Если вы обновили их, сохраните их. (Но прочитайте примечание ниже)
* ** works \\loadedchapters.db ** - Как видно из названия, загруженные (но не любимые) главы манги. Если удалить, fmd может найти их снова.
* ** works \\ downloads.db ** - Активный список загрузки, загруженный, но не удаленный или еще не запущенный. Если удалить, придется добавить снова.
* ** works \\ Favorites.db ** - Избранное. Сохраняет ссылки на любимые манги и т. Д.

Не делайте резервную копию config / base.ini, потому что вам нужен base.ini из этой вилки, чтобы получать обновления и т. Д.!

После резервного копирования этих файлов снова установите FMD.

Примечание для файлов данных: если манга изменила свои страницы манги (например, с a.com/manga на a.com/mangas/manga), ваша база данных избранного и / или манга для этого сайта может не работать.

**Comment by Weeggllss** [comment]
I didn't put a new version on top of an old one. And I don't need to save any of its settings or favorites. The old version I just gave as an example that many sites with manga were present in the program.
![ScreenShot1](https://user-images.githubusercontent.com/64138497/80024121-3df50100-84e7-11ea-8513-a2d5bf1c37c2.png)
![ScreenShot2](https://user-images.githubusercontent.com/64138497/80024130-43524b80-84e7-11ea-9e8d-60cfc042669b.png)
![ScreenShot3](https://user-images.githubusercontent.com/64138497/80024134-451c0f00-84e7-11ea-89a6-468f69a4850c.png)
![ScreenShot5](https://user-images.githubusercontent.com/64138497/80024136-464d3c00-84e7-11ea-9a95-015a042a0f55.png)

**Comment by Tmp341** [comment]
Extract this in your config folder:

[config.zip](https://github.com/fmd-project-team/FMD/files/4520812/config.zip)

**Comment by Weeggllss** [comment]
when trying to update modules it returns an error
![ScreenShot7](https://user-images.githubusercontent.com/64138497/80140943-5fbaba80-85b1-11ea-9f20-05149146147d.png)

**Comment by Tmp341** [comment]
Have you tried a VPN?

**Comment by Weeggllss** [comment]
anytime

**Comment by Tmp341** [comment]
Download latest version again, and extract it in a different folder then try again.

**Comment by Weeggllss** [comment]
Я пробовал установку в разные папки, разные интернет-соединения, отключал антивирус и отключал встроенный файрволл Windows. К сожалению это не работает для меня. Обновление модулей не происходит.

**Comment by Weeggllss** [comment]
I downloaded and unpacked the files to a folder whose path does not contain a Cyrillic font. And it worked. At least I can't find any other reason.
Thank you for your help.

**Comment by Tmp341** [comment]
Oh, FMD doesn't work with folder paths contains characters like Cyrillic.
